import { Component, signal, computed, OnInit, OnDestroy } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { ChevronLeft, ChevronRight, Users, CheckCircle, Zap, LucideAngularModule } from 'lucide-angular';

interface HeroSlide {
  id: number;
  heading: string;
  description: string;
  backgroundImage: string;
}

interface BenefitTab {
  id: string;
  label: string;
  title: string;
  benefits: string[];
}

interface Testimonial {
  quote: string;
  author: string;
  role: string;
  image: string;
}

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [RouterLink, CommonModule, LucideAngularModule],
  templateUrl: './home.html',
  styleUrl: './home.css'
})
export class HomeComponent implements OnInit, OnDestroy {
  // Lucide icons
  readonly ChevronLeft = ChevronLeft;
  readonly ChevronRight = ChevronRight;

  // Benefits Section Data
  readonly benefitsTabs: BenefitTab[] = [
    {
      id: 'consumers',
      label: 'Consumers',
      title: 'For Home & Everyday Use',
      benefits: [
        'Access affordable and reliable solar energy directly from local producers.',
        'Reduce your electricity bills and gain energy independence.',
        'Monitor your energy consumption and savings in real-time.',
        'Contribute to a greener environment by utilizing clean energy.'
      ]
    },
    {
      id: 'prosumers',
      label: 'Prosumers',
      title: 'Maximize Your Solar Investment',
      benefits: [
        'Sell excess energy generated by your solar panels to neighbors or the grid.',
        'Earn extra income and shorten the payback period of your installation.',
        'Optimize energy usage with smart analytics and trading tools.',
        'Play a key role in stabilizing the local energy community.'
      ]
    },
    {
      id: 'utilities',
      label: 'Utilities',
      title: 'Modernize & Stabilize the Grid',
      benefits: [
        'Seamlessly integrate distributed energy resources (DERs) into the grid.',
        'Reduce peak load demand and defer expensive infrastructure upgrades.',
        'Gain real-time visibility into grid edge performance and stability.',
        'Foster stronger customer engagement with innovative energy services.'
      ]
    }
  ];

  // State
  activeTab = signal<string>('consumers');

  setActiveTab(tabId: string): void {
    this.activeTab.set(tabId);
  }

  get currentBenefitTab(): BenefitTab {
    return this.benefitsTabs.find(tab => tab.id === this.activeTab()) || this.benefitsTabs[0];
  }

  // Carousel data structure - easily modifiable
  private readonly heroSlides: HeroSlide[] = [
    {
      id: 1,
      heading: 'Decentralized Energy Trading',
      description: 'Tumi connects households and institutions across Ghana in a regulated marketplace where energy flows freely and savings run deep. Buy local. Sell surplus. Keep the grid steady.',
      backgroundImage: '/assets/hero-slide-1.png'
    },
    {
      id: 2,
      heading: 'Smart Energy Management',
      description: 'Monitor your energy consumption in real-time and optimize your usage with our intelligent platform. Save money while contributing to a sustainable future.',
      backgroundImage: '/assets/hero-slide-2.png'
    },
    {
      id: 3,
      heading: 'Renewable Energy Solutions',
      description: 'Join thousands of households generating clean energy and earning from their surplus. Be part of Ghana\'s renewable energy revolution.',
      backgroundImage: '/assets/hero-slide-3.png'
    }
  ];

  // Reactive state using Signals
  currentSlideIndex = signal(0);
  isHovered = signal(false);

  // Computed values
  currentSlide = computed(() => this.heroSlides[this.currentSlideIndex()]);
  totalSlides = computed(() => this.heroSlides.length);

  // Auto-play interval
  private autoPlayInterval?: ReturnType<typeof setInterval>;
  private readonly AUTO_PLAY_DURATION = 10000; // 10 seconds

  ngOnInit(): void {
    this.startAutoPlay();
  }

  ngOnDestroy(): void {
    this.stopAutoPlay();
  }

  // Navigation methods
  nextSlide(): void {
    const nextIndex = (this.currentSlideIndex() + 1) % this.totalSlides();
    this.currentSlideIndex.set(nextIndex);
  }

  previousSlide(): void {
    const prevIndex = this.currentSlideIndex() === 0
      ? this.totalSlides() - 1
      : this.currentSlideIndex() - 1;
    this.currentSlideIndex.set(prevIndex);
  }

  goToSlide(index: number): void {
    this.currentSlideIndex.set(index);
  }

  // Features Data
  readonly features = [
    {
      title: 'Peer-to-Peer Trading',
      description: 'Connect directly with energy producers and consumers to trade excess electricity efficiently.',
      icon: Users,
      image: '/assets/placeholder-image.svg'
    },
    {
      title: 'Certified Solar Solutions',
      description: 'Access verified solar panels and services from trusted certified vendors to maximize your returns.',
      icon: CheckCircle,
      image: '/assets/placeholder-image.svg'
    },
    {
      title: 'Utility Integration',
      description: 'Seamlessly integrates with existing utility grids for a hybrid energy experience.',
      icon: Zap,
      image: '/assets/placeholder-image.svg'
    }
  ];

  // Statistics Data
  readonly stats = {
    activeTraders: '2,847 +',
    kwhTraded: '1.2M',
    evPoints: '847 +',
    gridStability: '99.9%'
  };

  // Testimonials Data
  readonly testimonials: Testimonial[] = [
    {
      quote: "Tumi has transformed how my family accesses energy. It's affordable, reliable, and I love being part of Ghana's solar revolution!",
      author: 'Abena Serwaa',
      role: 'Homeowner, Accra',
      image: '/assets/placeholder-image.svg'
    },
    {
      quote: "Selling my excess solar power has added a new revenue stream for my business. The platform is incredibly easy to use and fair.",
      author: 'Kwame Asare',
      role: 'Small Business Owner, Kumasi',
      image: '/assets/placeholder-image.svg'
    },
    {
      quote: "The data insights from Tumi are invaluable for optimizing our grid. It's a smart solution for sustainable energy management.",
      author: 'Helena Mensah',
      role: 'Energy Analyst, Volta Region',
      image: '/assets/placeholder-image.svg'
    }
  ];

  // Auto-play control
  private startAutoPlay(): void {
    this.autoPlayInterval = setInterval(() => {
      if (!this.isHovered()) {
        this.nextSlide();
      }
    }, this.AUTO_PLAY_DURATION);
  }

  private stopAutoPlay(): void {
    if (this.autoPlayInterval) {
      clearInterval(this.autoPlayInterval);
    }
  }

  onMouseEnter(): void {
    this.isHovered.set(true);
  }

  onMouseLeave(): void {
    this.isHovered.set(false);
  }
}
