import { Component, OnInit, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AdminLayoutComponent } from '../../admin-layout/admin-layout';
import { AuthService } from '../../../../services/auth.service';
import { EstimationsService } from '../../../../services/estimations.service';
import { LucideAngularModule, LayoutDashboard, ShoppingBag, History, Settings, Download, FileText, ClipboardCheck } from 'lucide-angular';

@Component({
  selector: 'app-customer-estimations',
  standalone: true,
  imports: [CommonModule, RouterModule, AdminLayoutComponent, LucideAngularModule],
  templateUrl: './estimations.html'
})
export class CustomerEstimationsComponent implements OnInit {
  private authService = inject(AuthService);
  private estimationsService = inject(EstimationsService);

  userName = signal('');
  userRole = signal('');
  userInitials = signal('');
  estimationToken = signal<string | null>(null);
  estimationData = signal<any>(null);

  readonly LayoutDashboard = LayoutDashboard;
  readonly ShoppingBag = ShoppingBag;
  readonly History = History;
  readonly Settings = Settings;
  readonly Download = Download;
  readonly FileText = FileText;
  readonly ClipboardCheck = ClipboardCheck;

  ngOnInit(): void {
    const user = this.authService.currentUser();
    if (user) {
      this.userName.set(`${user.first_name} ${user.last_name}`);
      this.userRole.set(user.role);
      this.userInitials.set(`${user.first_name?.[0] || 'U'}${user.last_name?.[0] || ''}`);
    }

    const token = localStorage.getItem('estimation_token');
    if (token) {
      this.estimationToken.set(token);
      this.loadEstimation(token);
    }
  }

  loadEstimation(token: string) {
    this.estimationsService.getGuestEstimationByCode(token).subscribe({
      next: (res) => {
        if (res.success) {
          this.estimationData.set(res.data);
        }
      },
      error: () => console.error('Failed to load estimation')
    });
  }

  downloadPDF() {
    const data = this.estimationData();
    if (!data) return;

    const content = this.generatePDFContent(data);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `estimation-${this.estimationToken()}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);
  }

  private generatePDFContent(data: any): string {
    return `
TUMI SOLAR ESTIMATION REPORT
============================

Token: ${this.estimationToken()}
Date: ${new Date().toLocaleDateString()}

ENERGY SUMMARY
--------------
Total Power: ${data.total_watts}W
Daily Usage: ${data.daily_kwh} kWh
Monthly Usage: ${data.monthly_kwh} kWh
Estimated Monthly Cost: GH₵${data.estimated_monthly_cost}

APPLIANCES
----------
${data.appliances_breakdown?.map((app: any) => 
  `- ${app.name}: ${app.wattage}W x ${app.quantity} (${app.daily_usage_hours}h/day)`
).join('\n')}

Generated by Tumi Solar Configurator
    `.trim();
  }
}
